/* 
 * securityapi
 *
 * The security APIs help you detect and block security threats.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.Security.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.Security.Model
{
    /// <summary>
    /// Result of performing an SQL Injection protection operation
    /// </summary>
    [DataContract]
    public partial class StringSqlInjectionDetectionResult :  IEquatable<StringSqlInjectionDetectionResult>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StringSqlInjectionDetectionResult" /> class.
        /// </summary>
        /// <param name="successful">True if the operation was successful, false otherwise.</param>
        /// <param name="containedSqlInjectionAttack">True if the input contained SQL Injection attacks, false otherwise.</param>
        /// <param name="originalInput">Original input string.</param>
        public StringSqlInjectionDetectionResult(bool? successful = default(bool?), bool? containedSqlInjectionAttack = default(bool?), string originalInput = default(string))
        {
            this.Successful = successful;
            this.ContainedSqlInjectionAttack = containedSqlInjectionAttack;
            this.OriginalInput = originalInput;
        }
        
        /// <summary>
        /// True if the operation was successful, false otherwise
        /// </summary>
        /// <value>True if the operation was successful, false otherwise</value>
        [DataMember(Name="Successful", EmitDefaultValue=false)]
        public bool? Successful { get; set; }

        /// <summary>
        /// True if the input contained SQL Injection attacks, false otherwise
        /// </summary>
        /// <value>True if the input contained SQL Injection attacks, false otherwise</value>
        [DataMember(Name="ContainedSqlInjectionAttack", EmitDefaultValue=false)]
        public bool? ContainedSqlInjectionAttack { get; set; }

        /// <summary>
        /// Original input string
        /// </summary>
        /// <value>Original input string</value>
        [DataMember(Name="OriginalInput", EmitDefaultValue=false)]
        public string OriginalInput { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StringSqlInjectionDetectionResult {\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  ContainedSqlInjectionAttack: ").Append(ContainedSqlInjectionAttack).Append("\n");
            sb.Append("  OriginalInput: ").Append(OriginalInput).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StringSqlInjectionDetectionResult);
        }

        /// <summary>
        /// Returns true if StringSqlInjectionDetectionResult instances are equal
        /// </summary>
        /// <param name="input">Instance of StringSqlInjectionDetectionResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StringSqlInjectionDetectionResult input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Successful == input.Successful ||
                    (this.Successful != null &&
                    this.Successful.Equals(input.Successful))
                ) && 
                (
                    this.ContainedSqlInjectionAttack == input.ContainedSqlInjectionAttack ||
                    (this.ContainedSqlInjectionAttack != null &&
                    this.ContainedSqlInjectionAttack.Equals(input.ContainedSqlInjectionAttack))
                ) && 
                (
                    this.OriginalInput == input.OriginalInput ||
                    (this.OriginalInput != null &&
                    this.OriginalInput.Equals(input.OriginalInput))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Successful != null)
                    hashCode = hashCode * 59 + this.Successful.GetHashCode();
                if (this.ContainedSqlInjectionAttack != null)
                    hashCode = hashCode * 59 + this.ContainedSqlInjectionAttack.GetHashCode();
                if (this.OriginalInput != null)
                    hashCode = hashCode * 59 + this.OriginalInput.GetHashCode();
                return hashCode;
            }
        }
    }

}
